### ISSUE TITLE
facing an error while running nemo_2b_bf16_tp1_client (CPU)

### ISSUE THREAD

**Issue by TanmayDoesAI** [camenduru/nvidia-llm-colab#1]
![nvideallm](https://user-images.githubusercontent.com/85993243/235872238-f6387369-17b9-464e-8fc3-95e12c17101c.png)

**Comment by camenduru** [comment]
Hi @TanmayDoesAI 👋 please check this https://www.youtube.com/watch?v=wER54k32qXE I think the model is not ready 😋
